### ISSUE TITLE
WikiHouse plugin should be restructured as an 'extension' to simplify user installs

### ISSUE THREAD

**Issue by jbacus** [tav/wikihouse-plugin#2]
In a recent build of SketchUp 8, we introduced a simplified system for distributing Ruby scripts such that they may be more conveniently installed by users. A simple process for building "SketchUp Extensions" is described in [this blog post](http://sketchupapi.blogspot.com/2011/12/rbzs-in-sketchup-8m2-distribute-your.html).

**Comment by MrKriss** [comment]
I too was thinking this would be a good idea. Also because it lets you turn on/off the Extensions which would help with testing new features/versions of the plugin etc. 

I'll have a crack at doing this.

**Comment by MrKriss** [comment]
Ok, so I've got the plugin working as a SketchUp extension and tested it on Mac OS. Its all good to go on my folk.

Before pulling this in though, the website link for downloading it will need changing, as the main file to download is now a .rbz file. Also, download/install instructions will need updating on the web page. 

I'm not familiar with the website code enough to do this yet. I'll ask someone to do this on the group tomorrow.

**Comment by thruflo** [comment]
Hey @MrKriss I can update the website.  As well as link, we should also presumably change some wording in a few places ("plugin" to "extension").

I have write access to this main wikihouse-plugin repo, so if @tav's happy with the pull request, I can coordinate the timing to merge it and deploy the new website version.

**Comment by tav** [comment]
Definite :+1: on turning the plugin into an `.rbz` extension. As for the pull request, I'm not a fan of putting release binaries into git repositories. So it would be awesome if you could instead write a `Makefile` which:
- Generates `sketchup/wikihouse.rbz` and `sketchup/wikihouse-{git-rev}.rbz` on `make build`.
- Uploads both files via `s3put -b wikihouse` on `make release`.

You can find the current `git-rev` by running:

``` bash
$ git rev-parse --short=8 HEAD
```

This way we would have a unique file available for download for each release and the latest release will always be available at the canonical:
- https://wikihouse.s3.amazonaws.com/sketchup/wikihouse.rbz

I've just created the `wikihouse` bucket on [S3](http://aws.amazon.com/s3/) and will share the credentials with @thruflo so that once the pull request comes through and is merged, he can do the release and update the site. Thanks guys!

P.S. It'd be nice to also have a `.gitignore` file which ignores the `sketchup/*.rbz` files as part of the pull request :smiley:

**Comment by MrKriss** [comment]
Sounds good. Ok, I'll have a look at doing this, though I have no prior experience writing make files. (If someone feels they can do this in a fraction of the time by all means feel free :smiley: )  

The .rbz file itself is simply a .zip file renamed with a different suffix so that SketchUp recognises it as an extension. It currently contains a sub folder (which I've named `wikihouse-plugin` in my folk) and a short `load_wikihouse_extension.rb` script. The sub folder then contains the `wikihouse-assets` folder and main `wikihouse.rb` script, which are both copied over to the plugins directory automatically when the .rbz file is loaded

Also, I agree with thruflo, having both "plugin" and "extension" is somewhat confusing when they are essentially the same thing. Renaming to "extension" would sort this out.

**Comment by MrKriss** [comment]
Ok, I'm nearly done on this and will be submitting a pull request shortly.  The only thing I haven't been able to check is whether the amason `s3put` commands I have written are correct. All that should need changing though is the `wikihouse_bucket` variable to point to the appropriate location.

Main additions:
- `make` or `make build` now generates `wikihouse_extension.rbz` 
- `make release` _should_ upload following to Amazon S3 bucket:
  - `wikihouse_extension.rbz` and `wikihouse_extension-{git-rev}.rbz`
- Included `.gitignore` for .rbz files
- Renamed all instances of plugin to extension for clarity. 
- Updated install instruction in README

**Comment by thruflo** [comment]
Hey @MrKriss this looks great!  Sorry for the slow response.

@tav are you happy to merge this?  Am I blocking anything / let me know next step...
